# Wait 10 milliseconds for starship to check files under the current directory
scan_timeout = 10

# Disable the blank line at the start of the prompt
add_newline = false

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Disable the package module, hiding it from the prompt completely
[username]
disabled = true

[gcloud]
disabled = true

[aws]
disabled = true

[line_break]
disabled = false

[directory]
truncation_length = 3
read_only = " ğŸ”’"

[git_branch]
symbol = "î‚  "

[git_commit]
commit_hash_length = 7
format = "on [$hash]($style) "
tag_symbol = 'ğŸ”– '

[git_status]
ahead = 'â‡¡${count}'
diverged = 'â‡•â‡¡${ahead_count}â‡£${behind_count}'
behind = 'â‡£${count}'

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = '[ğŸ’ PICKING](bold red)'

[git_metrics]
disabled = false
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[hg_branch]
symbol = "î‚  "

[nodejs]
format = 'via [ğŸ¤– $version](bold green) '

[rust]
format = 'via [Rust $version](red bold)'
symbol = 'ğŸ¦€ '

[golang]
format = 'via [Go $version](bold cyan) '

[lua]
format = 'via [Lua $version](bold blue) '

[zig]
symbol = 'âš¡ï¸ zig '

[direnv]
disabled = false

[sudo]
style = 'bold green'
symbol = 'ğŸ‘©â€ğŸ’» <200d>'
disabled = false

